prompt:
  instruction: >-
    Extract keywords from this text
  demonstration: []
  completion: >-
    keywords:
openai:
  model: text-davinci-003
  temperature: 0.7
  max_tokens: 256
  top_p: 1
  frequency_penalty: 0
  presence_penalty: 0
